version: "3"

services:
  app:
    image: simplycodedsoftware/php:8.0
    volumes:
      - "$PWD:/data/app"
    user: 1000:1000
    working_dir: "/data/app"
    command: sleep 99999
    networks:
      - default
    environment:
      RABBIT_HOST: "rabbitmq"
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - default
    ports:
      - "15673:15672"
networks:
  default:
    external:
      name: ecotone-test